<!-- 
save as 'gse.Rmd'
child of 'report.Rmd'
--> 





<!--make subsection for every gene set enrichment analysis-->
```{r gse_eval, include=FALSE, message=FALSE}
gseBool <- rep(FALSE, 20)
if(length(geneList$GSE) != 0) gseBool[1:length(geneList$GSE)] <- TRUE
counter <- 1
```

```{r, results='asis', eval=gseBool[counter]}
if(length(geneList$GSE) != 0){
  cat("# Gene Set Enrichment Analysis\n\n")
  cat("
  Gene Set Analysis was carried out using the Enrichr API.
Each analysis was presented with the Enrichr Combined Score, which is a combination of both the p-value and z-score. 
For more information on EnrichR visit the [website](http://amp.pharm.mssm.edu/Enrichr/) or see these publications [^fn10], [^fn11].

[^fn10]: Enrichr: interactive and collaborative HTML5 gene list enrichment analysis tool. Chen EY, Tan CM, Kou Y, Duan Q, Wang Z, Meirelles GV, Clark NR, Ma'ayan A. BMC Bioinformatics. 2013;128(14)
[^fn11]: Enrichr: a comprehensive gene set enrichment analysis web server 2016 update. Kuleshov MV, Jones MR, Rouillard AD, Fernandez NF, Duan Q, Wang Z, Koplev S, Jenkins SL, Jagodnik KM, Lachmann A, McDermott MG, Monteiro CD, Gundersen GW, Ma'ayan A. Nucleic Acids Research. 2016; gkw377.    
  ")
}
```


```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```

```{r, eval=gseBool[counter], child='gseChild.Rmd'}
```
